### ISSUE TITLE
Event render cause wrong event.column

### ISSUE THREAD

**Issue by JJTOkenizer** [mherrmann/fullcalendar-columns#12]
After spending many hours to understand what causes this bug (after I explain in more detail), updating plugins (jquery, fullcalendar and stuff) I finally figured out what's going on.
The version of FullCalendar that I'm using is the 2.3.1

Now the main problem is that if I move an event from the column 0 to the same column that I will get the event was moved to column 1. Almost always the event is moved to the next column and this is wrong. In jsfiddle you can verify this malfunction. I do not understand why because this event render.

JSFIDDLE: http://jsfiddle.net/jc07k3dd/56/

incriminated code:

```
unavailablePeriod =
{
     'title': "unav",
     'start': start,
     'end': date_end,
     'allDay': false,
     'color': '#BEBEBE',
     'editable': false,
     'className': 'fc-unavailable',
     'column': 0
};
```

How can I fix?

**Comment by mherrmann** [comment]
I suspect that the same problem occurs also when you don't use
fullcalendar-columns. That is, when you have an unavailable event on a
Monday (say) in a normal calendar and try to drag an event over it, that
the event ends up on Tuesday. If that is the case then this is not a
"problem" of fullcalendar-columns but actually of FullCalendar itself.

On 9 November 2015 at 09:20, JJTOkenizer notifications@github.com wrote:

> After spending many hours to understand what causes this bug (after I
> explain in more detail), updating plugins (jquery, fullcalendar and stuff)
> I finally figured out what's going on.
> The version of FullCalendar that I'm using is the 2.3.1
> 
> Now the main problem is that if I move an event from the column 0 to the
> same column that I will get the event was moved to column 1. Almost always
> the event is moved to the next column and this is wrong. In jsfiddle you
> can verify this malfunction. I do not understand why because this event
> render.
> 
> JSFIDDLE: http://jsfiddle.net/jc07k3dd/56/
> 
> incriminated code:
> 
> unavailablePeriod =
> {
>      'title': "unav",
>      'start': start,
>      'end': date_end,
>      'allDay': false,
>      'color': '#BEBEBE',
>      'editable': false,
>      'className': 'fc-unavailable',
>      'column': 0
> };
> 
> How can I fix?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mherrmann/fullcalendar-columns/issues/12.

## 

[image: Inline image 1]

Michael Herrmann, MSc
Alser Straße 18/26
1090 Wien
Tel.: +43 699 11 65 16 40
Email: michael@herrmann.io

**Comment by JJTOkenizer** [comment]
@mherrmann 
Thanks for the reply.

How I can fix this? It's most important for me resolve this bug. What do you hint?

**Comment by mherrmann** [comment]
I don't know and don't have time to look into it in more detail. As always, I suggest you ask on StackOverflow. Or look through the FullCalendar documentation whether you can find something there.
Closing this issue.

**Comment by JJTOkenizer** [comment]
Okay @mherrmann just last question: There's another method instead of event render?

**Comment by mherrmann** [comment]
I don't know. As I repeatedly said, this is not a forum for FullCalendar questions. It doesn't help that you're creating new accounts all the time. Do your work yourself.
