### ISSUE TITLE
revertFunc() from eventDrop callback not setting event back to inital column

### ISSUE THREAD

**Issue by mitomm** [mherrmann/fullcalendar-columns#14]
First, thanks a lot for your plugin. I really like it.
However, I think I found a small bug.

Trying to use the reverFunc() as described here:
http://fullcalendar.io/docs/event_ui/eventDrop/

I noticed, that when an event is dragged to a different column and then tried to be "reverted" to where it came from, the column is not always properly "reverted".

To reproduce the error, check out this fiddle (http://jsfiddle.net/3p7g1zrn/2/) and follows those two steps:
1. Drag down the event inside the same column and confirm the change (by clicking "ok" twice)
2. Now drag the event to the other column and click "cancel" on the second alert window
In that case, the event does not jump bach to column 1. However, I also noticed, that if step 1 is not performed and one does immediately try step 2, it seems to work.

Thanks for your help.

Best regards,

Tom

**Comment by mherrmann** [comment]
Hi, thanks for the nice words.

I can confirm this bug exists. For me however, it already occurs when I click `cancel` the first time. The following `eventDrop` can be used to reproduce it:

```
eventDrop: function(event, delta, revertFunc) {
    if (!confirm("Are you sure about this change?")) {
        console.log("Reverting...");
        revertFunc();
    }
}
```

I briefly looked into finding a solution. I'm pretty certain the fix will be a pretty trivial code change. I don't have much time to look into this at the moment, so if you manage to come up with a fix then I'd be happy to accept a pull request. I think one just has to debug a little into FullCalendar/fullcalendar-columns to find a solution.

**Comment by mitomm** [comment]
I just fixed the bug and sent you a pull request. I actually just had to remove one line, although it took me some time to figure it out. ;) 

Best regards,

Tom

**Comment by mherrmann** [comment]
Great :+1: I've incorporated your change and released a new version. Thanks!

**Comment by Robertoart13** [comment]
Este me funciono a mi   eventDrop: function(info) {
    alert(info.event.title + " was dropped on " + info.event.start.toISOString());

    if (!confirm("Are you sure about this change?")) {
      info.revert();
    }
  }
