### ISSUE TITLE
Problem with background

### ISSUE THREAD

**Issue by AlexanderSutul** [mherrmann/fullcalendar-columns#25]
When I'm trying to do the things like = 
`id: data.id,
                        start: start,
                        end: end,
                        column: i,
                        rendering: 'background',
                        color: 'lightgray'`

for background, column doesn't work in some cases but in some cases do, please help me, deadline is coming!!!

**Comment by mherrmann** [comment]
I'm sorry but I also have deadlines coming and don't have time to look into this.

If you find a solution, I'd be happy to merge any Pull Requests.

**Comment by AlexanderSutul** [comment]
Could you give me a path to explore what to do? I don't even realise how to solve that issue...

**Comment by mherrmann** [comment]
I'm sorry I have no idea :/

**Comment by AlexanderSutul** [comment]
Ok then =(
