### ISSUE TITLE
problem with 8 columns per day

### ISSUE THREAD

**Issue by dmpicture** [mherrmann/fullcalendar-columns#3]
Hi Michael,
i want to use your fullcalendar-columns extension for a project and it´s  great. 
But I have a problem, if I try to use 8 columns per day, using the multiColAgendaWeek, I get displayed only Monday Tuesday Wednesday Thursday and Sunday and then resumes with the next week. If I try to use hiddenDays: [0, 6] to cut off the weekend it only prints the days Monday Tuesday Wednesday and then starts again with the next week. Where am I wrong?
Thank you very much for helping

**Comment by gretaq** [comment]
hi... I've figured it out. The problem is in the '_computeOriginalEvent' function, because of 'daysDelta' wrong calculation when the two dates differ by more than a month.
You just need to change daysDelta calculation with this: 

var daysDelta = start.diff(this.start, 'days');

Bye :)

**Comment by mherrmann** [comment]
Excellent, thanks @gretaq! :+1: I've released your changes as part of the latest version, v1.5.
