### ISSUE TITLE
Uncaught TypeError: Cannot read property 'class' of undefined

### ISSUE THREAD

**Issue by JackIlPAZZO** [mherrmann/fullcalendar-columns#5]
I'm using easyappointments.org plugin that's use the fullcalendar.min.js plugin, when I import the fullcalendar-column.js I get this error:

Uncaught TypeError: Cannot read property 'class' of undefined(anonymous function) @ fullcalendar-columns.js:10(anonymous function) @ fullcalendar-columns.js:214
jquery.min.js:3 POST http://localhost/Calendario/backend_api/ajax_get_calendar_appointments 500 (Internal Server Error)send @ jquery.min.js:3b.extend.ajax @ jquery.min.js:3b.(anonymous function) @ jquery.min.js:3BackendCalendar.refreshCalendarAppointments @ backend_calendar.js:1275(anonymous function) @ backend_calendar.js:244b.event.dispatch @ jquery.min.js:1v.handle @ jquery.min.js:1b.event.trigger @ jquery.min.js:1(anonymous function) @ jquery.min.js:2b.extend.each @ jquery.min.js:1b.fn.b.each @ jquery.min.js:1b.fn.extend.trigger @ jquery.min.js:2BackendCalendar.initialize @ backend_calendar.js:160(anonymous function) @ backend:145c @ jquery.min.js:1p.fireWith @ jquery.min.js:1b.extend.ready @ jquery.min.js:1H @ jquery.min.js:1

I noticed that this error disappear if I insert fullcalendar.js instead of fullcalendar-min.js, but I really need to use fullcalendar-min.js 

Why happean this?

**Comment by mherrmann** [comment]
Hi, which version of FullCalendar are you using?

**Comment by JackIlPAZZO** [comment]
I'm using 1.6.1 'cause the easyappointments.org library is based on this version. I guess the problem is on this line:

var AgendaView = fc.views.agenda.class || fc.views.agenda;

If I insert the new version 2.3.1 as you said in the doc all working but I've an error on this line:

 $('#calendar').fullCalendar('getView').visStart,
 $('#calendar').fullCalendar('getView').visEnd

that return me undefined, and also the css is broken, you can see my stackoverflow question here:

http://stackoverflow.com/questions/33233997/fullcalendargetview-visstart-return-undefined

I've update also the css to this version and now the style is fixed but I've also the visStart and visEnd undefined problem. How I can fix this?

**Comment by mherrmann** [comment]
I'm sorry I'm not familiar with version 1.6.1 of FullCalendar so I don't know how you can fix this. If you find a fix and want to submit a pull request (that also works with at least v2.3.1) I'd be happy to incorporate your changes. I'm closing this issue.

**Comment by JackIlPAZZO** [comment]
Okay I've fixed updating to 2.3.1 and all file relative to this. Thanks for the amazing code exactly what I need :)
